### PR TITLE
Flask Webserver Implemented for Running Generated Code In Session

### PR DESCRIPTION
**Pull request by kilometersvi**
Wrapped Blockly html in Flask webserver for live code execution environment. 

This creates new button "Run Code" which will allow users to run their code in the browser, and outputs the execution into the page. This is a very basic approach, more cleaning can be done (separate output div for terminal or wiping generated code from output div, real time terminal output, etc)

Exec() is called relatively safely by using RestrictedPython's safe_builtins. However, this prevents the use of the "import" keyword, so all generated import statements have to be manually imported beforehand. As such, if new blocks are added with imports, be sure to add them to exec_namespace.py (as well as to requirements.txt).

Execution on output from all blocks has not been tested, only a few.

Changelog:

- bug fixes:
    - css file matches reference in html
    - Readmes in documentation & root made to match
- Instructions for running on AWS added (I am using a school computer, so can’t install docker locally)
- Project ported to Flask web server for allowing live execution of generated code
- Directory structure changed to correctly reflect new folder structure

Next steps, if this Flask implementation is continued:
- Implement concurrent networking to allow Blockly outputDiv to show output terminal from code execution in real time (rather than all at once, like this quick implementation)
- Adjust blocks for generating ggplots to also have a ggsave() call, who’s filename is found from an AJAX call to the flask server
    - Create popup using js containing generated ggplot img

If this pull request is rejected, bug fixes from changelog should still be considered.

### CODE REVIEW

**Comment by minnayu** [comment]
Thanks for implementing the flask server, and I think we will make changes to the docker container setup for ease of testing.

**Comment by minnayu** [comment]
after we make changes to custom_blocks.js, what do you mean by "restart the docker container", we tried different ways to restart the flask server but the changes aren't reflected on the server webpage.

**Comment by kilometersvi** [comment]
my apologies for lack of documentation. your browser might be caching the updated js file. ensure cookies & cache for the site are wiped before restarting.

**Comment by kilometersvi** [comment]
oh I see. you need to remove and re-create the docker image. as it is set up, the docker file will copy the src to its dir once the image is created, but not when the docker image is restarted.

by doing this, your issue should be fixed. There may be solutions to prevent this from needing to occur with the use of the 'docker cp' command: https://www.baeldung.com/ops/docker-copying-files. with this command, you could do something like 'docker cp /src docker_image:/src

**Comment by minnayu** [comment]
rebuilding the Dockerfile seemed to work. I think we're going to refactor how the image is setup and also how the container is created, so that we don't have to rebuild the image every time we want to make changes. thanks!

**Comment by kilometersvi** [comment]
for sure! hope it could be helpful.

**Pull request merged**
